# documentation.yaml --- Update gh-pages when `main` is updated.
# Thanks to the CodeRefinery team for
# <https://coderefinery.github.io/documentation/gh_workflow/>, and to GitHub
# for <https://github.com/actions/starter-workflows/blob/main/pages/static.yml>.

name: Docs
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [$default-branch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || ((github.event_name == 'pull_request') && (github.event.pull_request.merged == true)) }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install dependencies
        run: make install-deps
      - name: Sphinx build
        run: make doc
      - name: Bundle
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'doc/build/html'
      - name: Deploy
        uses: actions/deploy-pages@v2
